source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Walhalla_Example', :exclusive => true do
  pod "Walhalla", :path => "../"
end

target 'Walhalla_Tests', :exclusive => true do
  pod "Walhalla", :path => "../"

  
end
